services:
  arelx:
    container_name: arelx-dev
    hostname: arelx-dev
# =[ To test image changes:
    build:
      context: ..
      dockerfile: dev/arelx.dockerfile
# ]=
#
# =[ To test the CI image:
#     image: ghcr.io/stackmystack/arel-extensions/arel-extensions:pr-25
#     platform: linux/amd64
# volumes:
#   gemstash_data_amd64:
# ]= You may have to set the platform of the gemstash image too.
