services:
  arelx:
    container_name: arelx-dev
    hostname: arelx-dev
    build:
      context: ..
      dockerfile: dev/arelx.dockerfile
    volumes:
      - gem_cache:/mise/installs/ruby

volumes:
  gem_cache:
