[mssql.arel_extensions-v1]
rails4_2 = ["2.5", "2.7", "jruby-9.2"]
rails5_2 = ["2.5", "2.7", "jruby-9.2"]
[mssql.arel_extensions-v2]
rails6 = ["2.5", "2.7", "3.0", "3.1", "3.2", "3.3"]
rails6_1 = ["2.5", "2.7", "3.0", "3.1", "3.2", "3.3"]
rails7 = ["3.0", "3.1", "3.2", "3.3", "jruby-9.4"]
rails7_1 = ["3.1", "3.2", "3.3", "jruby-9.4"]
[mysql.arel_extensions-v1]
rails4_2 = ["2.5", "2.7", "jruby-9.2"]
rails5_2 = ["2.5", "2.7", "jruby-9.2", "jruby-9.3"]
[mysql.arel_extensions-v2]
rails6 = ["2.5", "2.7", "3.1", "jruby-9.2", "jruby-9.3"]
rails6_1 = ["2.5", "2.7", "3.0", "3.1", "3.2", "3.3", "jruby-9.2", "jruby-9.3"]
rails7 = ["2.7", "3.0", "3.1", "3.2", "3.3"]
rails7_1 = ["2.7", "3.0", "3.1", "3.2", "3.3"]
[postgres.arel_extensions-v1]
rails4_2 = ["2.5", "2.7", "jruby-9.2"]
rails5_2 = ["2.5", "2.7", "jruby-9.2", "jruby-9.3"]
[postgres.arel_extensions-v2]
rails6 = ["2.5", "2.7", "3.1", "jruby-9.2", "jruby-9.3"]
rails6_1 = ["2.5", "2.7", "3.0", "3.1", "3.2", "3.3", "jruby-9.2", "jruby-9.3"]
rails7 = ["2.7", "3.0", "3.1", "3.2", "3.3"]
rails7_1 = ["2.7", "3.0", "3.1", "3.2", "3.3"]
[sqlite.arel_extensions-v1]
rails4_2 = ["2.5", "2.7", "jruby-9.2"]
rails5_2 = ["2.5", "2.7", "jruby-9.2", "jruby-9.3"]
[sqlite.arel_extensions-v2]
rails6 = ["2.5", "2.7", "3.1", "3.2", "jruby-9.2", "jruby-9.3"]
rails6_1 = ["2.5", "2.7", "3.0", "3.1", "3.2", "3.3", "jruby-9.2", "jruby-9.3"]
rails7 = ["2.7", "3.0", "3.1", "3.2", "3.3"]
rails7_1 = ["2.7", "3.0", "3.1", "3.2", "3.3"]
[to_sql.arel_extensions-v1]
rails4_2 = ["2.5", "2.7"]
rails5_2 = ["2.5", "2.7", "jruby-9.2", "jruby-9.3"]
[to_sql.arel_extensions-v2]
rails6 = ["2.5", "2.7", "3.1", "3.2", "jruby-9.2", "jruby-9.3"]
rails6_1 = ["2.5", "2.7", "3.0", "3.1", "3.2", "3.3", "jruby-9.2", "jruby-9.3"]
rails7 = ["2.7", "3.0", "3.1", "3.2", "3.3"]
rails7_1 = ["2.7", "3.0", "3.1", "3.2", "3.3"]
