name: PR Image

on:
  pull_request:
    branches:
      - master
    paths:
      - bin/build

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Do Something
        run: echo "hello, image"
