name: Build and Test

# Ruby + Rails Compatibility Matrix from here:
# https://www.fastruby.io/blog/ruby/rails/versions/compatibility-table.html

on: [push, pull_request]

jobs:
  job_build_gem:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [3.1, 3.0, 2.7, 2.5, jruby-9.2, jruby-9.3]
        rails: [7, 6_1, 6, 5_2]
        exclude: [
          {ruby: 3.1,       rails: 6  },
          {ruby: 3.1,       rails: 5_2},
          {ruby: 3.0,       rails: 6  },
          {ruby: 3.0,       rails: 5_2},
          {ruby: 2.7,       rails: 5_2},
          {ruby: 2.5,       rails: 7  },
          {ruby: jruby-9.2, rails: 7  },
          {ruby: jruby-9.3, rails: 7  },
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup gemspec
        if: ${{ matrix.rails != '5_2' }}
        run: |
          cp ./gemspecs/arel_extensions-v2.gemspec ./arel_extensions.gemspec
          cp ./version_v2.rb lib/arel_extensions/version.rb
          cp ./gemfiles/rails${{ matrix.rails }}.gemfile ./Gemfile
      - name: Build source gem
        run: gem build arel_extensions.gemspec
      - name: Upload source gem
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.ruby }}-${{ matrix.rails }}-gem
          path: "*.gem"

  job_test_windows:
    name: test mssql on windows
    needs: job_build_gem
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.1, 3.0, 2.7, 2.5]
        rails: [7, 6_1, 6, 5_2]
        exclude: [
          {ruby: 3.1,       rails: 6   },
          {ruby: 3.1,       rails: 5_2 },
          {ruby: 3.0,       rails: 6   },
          {ruby: 3.0,       rails: 5_2 },
          {ruby: 2.7,       rails: 5_2 },
          {ruby: 2.5,       rails: 7   },
          {ruby: jruby-9.2, rails: 7   },
          {ruby: jruby-9.2, rails: 6_1 },
          {ruby: jruby-9.2, rails: 6   },
          {ruby: jruby-9.3, rails: 7   },
          {ruby: jruby-9.3, rails: 6_1 },
          {ruby: jruby-9.3, rails: 6   },
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Install mssql
        uses: potatoqualitee/mssqlsuite@v1
        with:
          install: sqlengine, sqlclient, sqlpackage, localdb
          sa-password: Password12!
      - name: Set up Ruby
        uses: MSP-Greg/ruby-setup-ruby@win-ucrt-1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install required packages on Windows
        shell: cmd
        run: |
          ridk exec sh -c "pacman --sync --needed --noconfirm  ${MINGW_PACKAGE_PREFIX}-gcc"
      - name: Update system-wide gems
        run: gem update --system
      - name: Setup Gemfile
        if: ${{ matrix.rails != '5_2' }}
        run: |
          cp ./gemspecs/arel_extensions-v2.gemspec ./arel_extensions.gemspec
          cp ./version_v2.rb lib/arel_extensions/version.rb
          cp ./gemfiles/rails${{ matrix.rails }}.gemfile ./Gemfile
      - name: bundle install
        run: |
          bundle config set gemfile .\gemfiles\rails${{ matrix.rails }}.gemfile
          bundle install --verbose
      - name: Download gem from build job
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.ruby }}-${{ matrix.rails }}-gem
      - name: Install downloaded gem
        run: gem install --local *.gem --verbose
      - name: Run test mssql
        run: bundle exec rake test:mssql
